domain:
  ethereum: rontech
  ronin: ron
database:
  host: localhost
  user: postgres
  password: postgres
  port: 5432
  db_name: ronin_naming_service
  write_time_out: 15
  conn_max_life_time: 1
  max_open_conns: 100
  max_idle_conns: 10
  debug: true
server:
  host: 0.0.0.0
  port: 8080
ens:
  resolver: 0xaBC01D156B571AdC3548aD725a0e9d3D1412b5ef
  registry: 0x00000000000C2E074eC69A0dFb2997BA6C7d2e1e
  rpc: https://eth-goerli.g.alchemy.com/v2/czFN4ZNuqJdER88t9lLlwLv31kZsF9vC
  privateKey:
