# chainId: "0x1"
chainId: "0x5"
verbosity: 3
domain:
  ethereum: rontech
  ronin: ron
database:
  host: localhost
  user: postgres
  password: example
  port: 5432
  db_name: ronin_naming_service
  write_time_out: 15
  conn_max_life_time: 1
  max_open_conns: 100
  max_idle_conns: 10
  debug: true
listener:
  ethereum:
    contracts:
      seaport:
        address: "0x00000000006c3852cbef3e08e8df289169ede581"
        abi: "/Users/dien.transkymavis.com/Documents/andicrypt/Play-Around-BC/generated_contracts/Seaport.json"
        name: "Seaport Controller Proxy"
    # rpc: "https://eth-mainnet.g.alchemy.com/v2/-1vrdcvZqQkRoCznsrrs7Bv7lxrb6Txr"
    rpc: "https://eth-goerli.g.alchemy.com/v2/0EcWWGpuYHAOuXQhHeagpC_UhlEXvfYh"
    from_block: 9023330
    safe_block_range: 
    handlers:
      - contract: "seaport"
        event: "OrderCancelled"
        handler: "OrderCancelledHandler"
        description: "handle event of cancelling an order"
      - contract: "seaport"
        event: "OrderFulfilled"
        handler: "OrderFulfilledHandler"
        description: "handle event of fulfilling an order"
      - contract: "seaport"
        event: "OrderValidated"
        handler: "OrderValidatedHandler"
        description: "handle event of validating an order"
