chainId: "0x7e5"
verbosity: 3
domain:
  ethereum: rontech
  ronin: ron
database:
  host: localhost
  user: postgres
  password: postgres
  port: 5432
  db_name: ronin_naming_service
  write_time_out: 15
  conn_max_life_time: 1
  max_open_conns: 100
  max_idle_conns: 10
  debug: true
http:
  max_connection: 50
  max_idle_connection: 5
  max_idle_connection_per_host: 5
  timeout: 60
  rate_limit: 40
listener:
  contracts:
    seaport:
      address: "0x00000000006c3852cbef3e08e8df289169ede581"
      abi: "Seaport.json"
      name: "Seaport Controller Proxy"
  rpc: "https://eth-goerli.g.alchemy.com/v2/0EcWWGpuYHAOuXQhHeagpC_UhlEXvfYh"
  from_block: 20273267
  safe_block_range: 5
  handlers:
    - contract: "seaport"
      event: "OrderCancelled"
      handler: "OrderCancelledHandler"
      description: "handle event of cancelling an order"
    - contract: "seaport"
      event: "OrderFulfilled"
      handler: "OrderFulfilledHandler"
      description: "handle event of fulfilling an order"
    - contract: "seaport"
      event: "OrderValidated"
      handler: "OrderValidatedHandler"
      description: "handle event of validating an order"
